// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

import { offlineDB } from '@/lib/offline-db';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Fetch Wrapper offline - intercepts mutations when offline and queues them
const customOfflineFetch = async (url: RequestInfo | URL, options?: RequestInit): Promise<Response> => {
  const method = options?.method || 'GET';
  const urlString = url.toString();

  // --- MUTATIONS (POST/PATCH/PUT/DELETE) ---
  // If offline and it's a mutation, enqueue immediately without trying
  if (method !== 'GET' && !window.navigator.onLine) {
    console.log('[Offline] Enfileirando mutação offline:', method, urlString);
    return enqueueAndMock(url, options);
  }

  // --- ATTEMPT THE REAL REQUEST ---
  try {
    const response = await fetch(url, options);
    return response;
  } catch (error) {
    if (error instanceof TypeError) {
      // Network error on a mutation: enqueue for later sync
      if (method !== 'GET') {
        console.log('[Offline] Erro de rede, enfileirando mutação:', method, urlString);
        return enqueueAndMock(url, options);
      }

      // Network error on GET: let it bubble up as an error
      // TanStack Query will then fall back to cached data (if available)
      // DO NOT return fake empty data here — that would overwrite the cache!
      console.log('[Offline] GET falhou sem rede, TanStack Query usará cache:', urlString);
    }
    throw error;
  }
};

const enqueueAndMock = async (url: RequestInfo | URL, options?: RequestInit): Promise<Response> => {
  const method = options?.method || 'POST';
  const body = options?.body ? options.body.toString() : null;
  const urlString = url.toString();
  
  await offlineDB.enqueueRequest({
    url: urlString,
    method,
    body,
    headers: {},
  });

  return new Response(JSON.stringify([{ id: 'offline-pending', status: 'queued' }]), { 
    status: 200, 
    headers: { 'Content-Type': 'application/json' } 
  });
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: customOfflineFetch
  }
});